name: 'tahcu_app'

services:
  postgres:
    image: tahcu-postgres:v1
    container_name: postgres
    ports:
      - ${DATABASE_PORT}
    restart: always
    env_file:
      - ../../.env.production
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_db:/db/data
    cpus: '0.50'
    mem_limit: 250mb

  dragonfly:
    container_name: dragonfly
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    ports:
      - ${DRAGONFLY_PORT}
    restart: always
    volumes:
      - dragonfly:/dragonfly/data
    cpus: '0.50'
    mem_limit: 250mb
  tahcu:
    container_name: tahcu
    image: tahcu:v1
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    env_file:
      - ../../.env.production
    depends_on:
      - postgres
      - dragonfly
    cpus: '0.50'
    mem_limit: 500mb

volumes:
  postgres_db:
    external: true

  dragonfly:
    external: true
